# Generated by Django 4.1.2 on 2022-10-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=100)),
                ("Mobile", models.CharField(max_length=20)),
                ("Emp_Code", models.CharField(max_length=30)),
                (
                    "Position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Employee_Register.position",
                    ),
                ),
            ],
        ),
    ]
